internal/adapter/graphql/convert_plugin.go, internal/adapter/graphql/models_gen.go, internal/graphql/generated.go, internal/infrastructure/github/plugin_registry_test.go, pkg/plugin/metadata.go, schema.graphql
* Add a thumbnail, author on plugin metadata
=> feat: add thumbnail, author fields on plugin metadata query

internal/adapter/graphql/controller_layer.go, internal/adapter/graphql/convert_layer.go, internal/adapter/graphql/models_gen.go, internal/graphql/generated.go, internal/graphql/resolver_layer.go, schema.graphql
add `sceneId` field, `scene` resolver and `scenePlugin` resolver to `LayerItem`, `LayerGroup`, `Infobox`, `InfoboxField`, `MergedLayer`, `MergedInfobox`, and `MergedInfoboxField` in the GraphQL schema.
=> feat: add scenePlugin resolver to layers

internal/app/public.go, internal/usecase/interfaces/published.go
Reverts reearth/reearth-backend#17
I found that reearth-backend does not have issues about OGP image. reearth-web should be fixed to solve it.
=> revert: "fix: ogp image for published page"

internal/app/config.go
=> raise graphql complexity limit 4000->6000

internal/app/public.go, internal/app/published.go, internal/app/published_test.go, internal/usecase/interactor/published.go
- Fix published API: `GET /p/:name/` and `GET /p/:name/data.json`
- Add tests for published API
=> fix: published API

pkg/layer/merged.go, pkg/layer/merged_test.go, pkg/layer/merging/merger_test.go
=> fix: hide parent infobox fields when child infobox is not nil

internal/infrastructure/mongo/mongodoc/tag.go, internal/infrastructure/mongo/tag.go, internal/usecase/repo/tag.go, pkg/tag/group_builder.go, pkg/tag/item_builder.go
tag system repos, docs, and models
1- create tag system datalayer interface
2- implement the interface
3- create MongoDB persistent layer for tag system 
implement data persistent for memory
=> feat: tag system data-layer (mongo)

internal/adapter/gql/generated.go, internal/adapter/gql/gqlmodel/models_gen.go, internal/adapter/gql/resolver_mutation_tag.go, internal/usecase/interactor/tag.go, internal/usecase/interfaces/tag.go, pkg/tag/group.go, pkg/tag/group_builder.go, pkg/tag/group_test.go, schema.graphql
attach/detach tag item from tag group
test data
=> feat: attach/detach tag item from group

internal/infrastructure/mongo/mongodoc/scene.go
=> feat: cluster datalayer

internal/adapter/gql/generated.go, internal/adapter/gql/gqlmodel/convert_scene.go, internal/adapter/gql/gqlmodel/models_gen.go, internal/adapter/gql/resolver_mutation_scene.go, internal/infrastructure/mongo/mongodoc/scene.go, internal/usecase/interactor/scene.go, internal/usecase/interfaces/scene.go, schema.graphql
=> feat: cluster graphql/mongo

internal/app/appauth/storage.go, internal/app/jwt.go
- fix access token issuing
- remove default key selecting
=> feat: fix token issuing

codecov.yml
please refer to https://docs.codecov.com/docs/ignoring-paths
=> chore: fix codecov config

go.mod, go.sum, internal/app/app.go, internal/app/auth_server.go, internal/app/config.go, internal/app/jwt.go
=> feat: auth client support multi issuer

pkg/builtin/manifest.yml, pkg/builtin/manifest_ja.yml
- set infobox show title default value
- set infobox height description
=> feat: update infobox style fields

pkg/user/user.go, pkg/user/user_test.go
=> feat: validate password criteria

internal/app/auth_server.go, internal/app/config.go, internal/usecase/interactor/auth.go, pkg/auth/client.go
=> fix: load auth client domain from config

internal/app/app.go
=> fix: authentication server end points disabling config

internal/app/app.go
=> chore: add log for GraphQL Playground endpoint

internal/usecase/interactor/tag.go, pkg/tag/group.go, pkg/tag/group_test.go
add new method "addItem" to tag group
=> fix: createTagItem mutation

.github/workflows/deploy_test.yml, internal/infrastructure/mongo/auth_request_test.go
Test: mongo auth request
add unittest of FindByID in auth_request.go
=> test: unit test for mongo auth request repo

pkg/builtin/manifest.yml, pkg/builtin/manifest_ja.yml
I added config for builtin timeline widget in manifest.yml.
- run reearth-backend
- run reearth-web with https://github.com/reearth/reearth-web/pull/285
- then you can add timeline widget from side panel
- and you can operate timeline component
=> feat: setup timeline buitlin widget
