reearth/reearth-backend

- internal/graphql/resolver_property.go
- internal/graphql/resolver_property_test.go
When a dataset child layer is linked and overrides that link, the value isn't correctly merged.
Returned the overridden value if its overridden
By writing a unit test to test that case
Not sure if the solution may effect the other scenarios
> fix: dataset link merge bug #378

- pkg/layer/decoding/kml.go
Fix the bug that KML coordinates were not decoded for "\t" separator
replaced strings.Split() with strings.Fields() to cover all white spaces
separated coordinates for each white-space
> fix: KML coordinates splitting 

- gqlgen.yml
- internal/adapter/graphql/controller_layer.go
- internal/adapter/graphql/models_gen.go
- internal/adapter/graphql/scalar.go
- internal/graphql/generated.go
- internal/usecase/interactor/layer.go
- internal/usecase/interfaces/layer.go
- schema.graphql
Add ability to set the layer name from dataset column
- Extend AddLayerGroupInput to accept optional markerTitleFieldId
- Use selected Field value as layer name
specially the graphQL schema so we can start the front-end development
The layer primitive type was implemented I've just tested it
> feat: Refine dataset import

- internal/app/config.go
Fixes a bug where Asset images were not seen in local environment. The URL saved with the asset was just the file name.
Added default url to AssetBaseURL in config. Now local assets saved will default to `http://localhost:8080/assets/XX`
Created a new asset and checked if it is retrievable with the asset's URL on the front-end
Do I need a migration???
> fix: local asset bug

- internal/infrastructure/google/fetch.go
used url.URL to construct the sheet url
Closes reeath/reearth#96
> fix: google sheet import when its name contains unicode chars

- pkg/layer/decoding/geojson.go
- pkg/layer/decoding/geojson_test.go
skip a geoJSON feature when it doesn't has a geometry to decode
skip nil geos 
validation function
> fix: skip nil geometries

- internal/adapter/gql/generated.go
- internal/adapter/gql/gqlmodel/convert_property.go
- internal/adapter/gql/gqlmodel/models_gen.go
- internal/adapter/gql/loader_project.go
- internal/adapter/gql/resolver_mutation_scene.go
- internal/adapter/gql/resolver_property_schema.go
- internal/adapter/gql/resolver_query.go
- internal/usecase/interactor/scene.go
- internal/usecase/interfaces/scene.go
- pkg/scene/sceneops/plugin_migrator.go
- pkg/scene/widget_system.go
- pkg/scene/widget_system_test.go
- schema.graphql
- Delete deprecated fields in GraphQL schema
- Change the name of some types
- `updateWidget` and `removeWidget` mutation accepts widgetId instead of pluginId and extensionId so that they support multiple widgets completely
Manually tested by reearth-web and I confirmed it works
> refactor: reorganize graphql schema

- pkg/dataset/value.go
- pkg/dataset/value_optional.go
- pkg/dataset/value_optional_test.go
- pkg/property/merged.go
- pkg/property/value.go
- pkg/property/value_dataset.go
- pkg/property/value_dataset_test.go
- pkg/property/value_optional.go
- pkg/property/value_optional_test.go
- pkg/property/value_test.go
- pkg/value/bool.go
- pkg/value/bool_test.go
- pkg/value/latlng.go
- pkg/value/latlngheight.go
- pkg/value/number.go
- pkg/value/number_test.go
- pkg/value/optional.go
- pkg/value/optional_test.go
- pkg/value/string.go
- pkg/value/string_test.go
- pkg/value/url.go
- pkg/value/value.go
- pkg/value/value_test.go
- When exporting a scene, the values of some properties linked to the dataset would become null. This has been fixed.
- `pkg/value/OptionalValue` has been renamed to `Optional`.
- `pkg/value/Value.Cast` method has been added to allow type conversion of values. Also, some type conversions such as string to URL and URL to string are newly supported.
> fix: cast values, rename value.OptionalValue

- .env.example
- internal/app/auth_server.go
- internal/app/config.go
- internal/app/config_test.go
- internal/app/jwt.go
- internal/app/web.go
- fix config bugs
- add .env.example file
> fix: auth to work with zero config

- .github/renovate.json
Renovate bot didn't run at the scheduled time. There was a typo for each package rule (`packagePatterns` instead of `matchPackagePatterns`). This was the only issue I could see so should work now.
> ci: renovate bot not running on schedule

- .env.example
I changed the `secrit` to `secret` on `.env.samples` comment for `REEARTH_AUTHSRV_KEY` environment variable.
Didn't as this change is on a comment.
Nothing.
> chore: typo `secrit` on env example

- internal/adapter/gql/generated.go
- internal/adapter/gql/gqlmodel/convert_property.go
- internal/adapter/gql/gqlmodel/models_gen.go
- pkg/builtin/manifest.yml
- pkg/builtin/manifest_ja.yml
- pkg/property/schema_field_ui.go
- schema.graphql
- schemas/plugin_manifest.json
closes reearth/reearth#278
Users want to be able to set an opacity to map tiles. So, this adds opacity to tiles :P 
Added slider as an option to schema ui in plugin_manifest
Added Opacity field to tile in manifest w min 0 and max 1, default 1.
Updated appropriate domain models, converters, etc
Checked if I could view field in UI, has default and can be changed.
> feat: add an opacity slider to map tiles

- .github/workflows/ci.yml
- internal/infrastructure/mongo/asset_test.go
- internal/infrastructure/mongo/mongo_test.go
I have added initial unit testing for the MongoDB based on this issue for "small start" 👉  https://github.com/reearth/reearth/issues/273.
See details (requirements) in that issue.
I implemented one for a trial to avoid conflicts and decide how we are going to test this methods.
I have added unit test for the Asset repository's `FindByID` method.
Add unit tests for all methods for Assets or other repositories.
This is because I wanted to "start small" since we need to discuss the policy and the implementation design first so that we don't waste time.
The testings are done by the CI GitHub Actions workflow.
This can be also tested locally.
```shell
go test -timeout 30s -run '^TestFindByID$' github.com/reearth/reearth-backend/internal/infrastructure/mongo
REEARTH_DB=mongodb://localhost go …
```
> test: add Mongo Asset's `FindByID` unit testing

- internal/infrastructure/mongo/asset.go
- internal/infrastructure/mongo/dataset.go
- internal/infrastructure/mongo/dataset_schema.go
- internal/infrastructure/mongo/layer.go
- internal/infrastructure/mongo/plugin.go
- internal/infrastructure/mongo/project.go
- internal/infrastructure/mongo/property.go
- internal/infrastructure/mongo/property_schema.go
- internal/infrastructure/mongo/scene.go
- internal/infrastructure/mongo/tag.go
- internal/infrastructure/mongo/team.go
- internal/infrastructure/mongo/user.go
An error "$in needs an array" returns from MongoDB when `ids` arg of `internal/infrastrucutre/mongo.*.FindByIDs` methods is nil.
> fix: "$in needs an array" error from mongo FindByIDs

- .github/workflows/ci.yml
I have bumped the `actions/cache` GitHub Action to `v3`.
Modify any other things.
Ran the CI.
Check nothing is broken.
As far as I understand, there are no breaking changes in these version updates.
* Ref: [v3.0.0](https://github.com/actions/cache/releases/tag/v3.0.0)
> ci: bump `actions/cache` to `v3`

- go.mod
- go.sum
- internal/infrastructure/mongo/lock.go
Since the usage of rand.Intn was incorrect, the entire retry process of mongo lock was replaced by the library implementation.
> refactor: retry mongo lock

- pkg/builtin/manifest.yml
Key and default value updates required by https://github.com/reearth/reearth-web/pull/228
This property has not been used except tests so should take no effects on former projects.
update `scene3d` to `3d`
update `scene2d` to `2d`
> refactor: update scene mode key

- internal/app/usecase.go
- internal/infrastructure/memory/transaction.go
- internal/infrastructure/memory/transaction_test.go
- internal/infrastructure/mongo/mongodoc/client.go
- internal/usecase/interactor/asset.go
- internal/usecase/interactor/common.go
- internal/usecase/interactor/usecase.go
- internal/usecase/interactor/usecase_test.go
- internal/usecase/repo/container.go
- internal/usecase/repo/transaction.go
Due to the low readability of use cases, the following statements can be made more declarative:
- Whether the usecase uses a transaction
- Whether the usecase denies users who cannot read/write the specific scene and team
> refactor: declarative description of use case structure (asset only)

- internal/infrastructure/memory/container.go
- internal/infrastructure/memory/transaction.go
- internal/infrastructure/memory/transaction_test.go
- internal/usecase/interactor/asset.go
- internal/usecase/interactor/asset_test.go
- internal/usecase/interactor/layer_test.go
- internal/usecase/interactor/plugin_upload_test.go
- internal/usecase/interactor/property_test.go
- internal/usecase/interactor/team_test.go
- internal/usecase/interactor/usecase_test.go
- internal/usecase/interactor/user_signup_test.go
- pkg/util/now.go
- Fix an issue that assets are not saved when files are uploaded
- Add a unit test for asset usecase partially
- Refactor `memory.New`
- Change `memory.Transaction.committed` behavior
> fix: assets are not saved when files are uploaded

- gqlgen.yml
- internal/adapter/gql/generated.go
- internal/adapter/gql/gqlmodel/models_gen.go
- internal/adapter/gql/loader_dataset.go
- internal/adapter/gql/resolver_dataset_schema.go
- internal/infrastructure/memory/dataset.go
- internal/infrastructure/mongo/dataset.go
- internal/usecase/interactor/dataset.go
- internal/usecase/interfaces/dataset.go
- internal/usecase/repo/dataset.go
- schema.graphql
I fixed reearth/reearth#267.
- add `CountBySchema` method to count dataset by schema id.
- add totalCount resolver to DatasetSchema struct
1. run reearth-backend and reearth-web
2. add dataset
3. check dataset count
> feat: add totalCount field to DatasetSchema type of GraphQL schema
